### PR TITLE
Calculate angular difference on camera rather than on the sky

### PR DESCRIPTION
**Pull request by orelgueta**
Change the calculation of the angular difference, add the threshold array, few other minor changes.

### CODE REVIEW

**Comment by TarekHC** [comment]
Hi @orelgueta 

Ok, this was probably a mistake: now the "selected_models" variable within "tain_models.py" does not have a single model uncommented (so it is empty).

What is the best model right now (is it still `MLP_tanh`)? Did you intend to do this?

Tarek

**Comment by orelgueta** [comment]
No, this was not intended and probably happened in the merge actually (my local version has `MLP_tanh` uncommented). That is the best model at the moment, yes.

**Comment by orelgueta** [comment]
I fixed it in the main branch now.

**Comment by TarekHC** [comment]
Thanks!

**Pull request merged**
